name: Docker Compose
description: Run any CI step in isolated Docker containers using Docker Compose
author: https://github.com/buildkite
requirements:
  - docker
  - docker-compose
configuration:
  properties:
    run:
      type: string
    build:
      type: [ string, array ]
      minimum: 1
    push:
      type: [ string, array ]
      minimum: 1
    pull:
      type: [ string, array ]
      minimum: 1
    config:
      type: [ string, array ]
      minimum: 1
    env:
      type: [ string, array ]
      minimum: 1
    environment:
      type: [ string, array ]
      minimum: 1
    args:
      type: [ string, array ]
      minimum: 1
    build-alias:
      type: [ string, array ]
      minimum: 1
    image-repository:
      type: string
    image-name:
      type: string
    pull-retries:
      type: integer
    push-retries:
      type: integer
    cache-from:
      type: [ string, array ]
      minimum: 1
    volumes:
      type: [ string, array ]
      minimum: 1
    expand-volume-vars:
      type: boolean
    command:
      type: array
    skip-checkout:
      type: boolean
    leave-volumes:
      type: boolean
    no-cache:
      type: boolean
    use-aliases:
      type: boolean
    tty:
      type: boolean
    dependencies:
      type: boolean
    ansi:
      type: boolean
    verbose:
      type: boolean
    workdir:
      type: string
    rm:
      type: boolean
    skip-pull:
      type: boolean
    upload-container-logs:
      type: string
    propagate-uid-gid:
      type: boolean
    propagate-environment:
      type: boolean
    mount-ssh-agent:
      type: boolean
    mount-buildkite-agent:
      type: boolean
    entrypoint:
      type: string
    cli-version:
      type: string
      enum:
        - 1
        - 2
  anyOf:
    - required:
      - run
    - required:
      - build
    - required:
      - push
  additionalProperties: false
  dependencies:
    ansi: [ run ]
    cache-from: [ build ]
    dependencies: [ run ]
    env: [ run ]
    environment: [ run ]
    expand-volume-vars: [ volumes ]
    image-repository: [ build ]
    image-name: [ build ]
    leave-volumes: [ run ]
    mount-buildkite-agent: [ run ]
    propagate-uid-gid: [ run ]
    pull: [ run ]
    push-retries: [ push ]
    skip-pull: [ run ]
    tty: [ run ]
    use-aliases: [ run ]
    user: [ run ]
    volumes: [ run ]
    workdir: [ run ]
